DROP DATABASE  IF EXISTS TCC_DB;
CREATE DATABASE TCC_DB;
USE TCC_DB;

CREATE TABLE tbl_Materia (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL
);

CREATE TABLE tbl_Imagem (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tbl_Usuario (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Sobrenome VARCHAR(200) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Senha VARCHAR(10) NOT NULL,
    ID_Imagem INT
);

CREATE TABLE tbl_Task (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    HTML_Text TEXT
);

CREATE TABLE tbl_Questao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Pergunta TEXT,
    ID_Imagem INT
);

CREATE TABLE tbl_Alternativa (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Opcao CHAR(1) NOT NULL,
    Status INT NOT NULL,
    Descricao TEXT NOT NULL,
    ID_Questao INT NOT NULL
);

CREATE TABLE tbl_Resolucao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Descricao TEXT,
    ID_Imagem INT,
    ID_Questao INT NOT NULL
);

CREATE TABLE tbl_Item_Questao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_Task INT NOT NULL,
    Questao_ID INT NOT NULL,
    Num_Ordem INT NOT NULL
);

CREATE TABLE tbl_ImagemXTask (
	ID_Imagem INT,
    ID_Task INT,
    PRIMARY KEY(ID_Imagem, ID_Task)
);

CREATE TABLE tbl_UsuarioXTask (
    ID_Usuario INT,
    ID_Task INT,
    PRIMARY KEY (ID_Usuario, ID_Task)
);

CREATE TABLE tbl_TaskXMateria (
    ID_Materia INT,
    ID_Task INT,
    PRIMARY KEY (ID_Materia, ID_Task)
);

CREATE TABLE tbl_Resposta (
    ID_Usuario INT NOT NULL,
    ID_ItemQuestao INT NOT NULL,
    Alternativa CHAR(1),
    Texto_Dissertativo TEXT,
    ID_Imagem INT,
    PRIMARY KEY (ID_ItemQuestao, ID_Usuario)
);

ALTER TABLE tbl_Usuario ADD CONSTRAINT FK_Imagem_Usuario
FOREIGN KEY (ID_Imagem)
REFERENCES tbl_Imagem (ID)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE tbl_Questao ADD CONSTRAINT FK_Imagem_Questao
FOREIGN KEY (ID_Imagem)
REFERENCES tbl_Imagem (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE tbl_Resposta ADD CONSTRAINT FK_Imagem_Resposta
FOREIGN KEY (ID_Imagem)
REFERENCES tbl_Imagem (ID)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE tbl_Resolucao ADD CONSTRAINT FK_Questao_Resolucao
FOREIGN KEY (ID_Questao)
REFERENCES tbl_Questao (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_Item_Questao ADD CONSTRAINT FK_Task_ItemQuestao
FOREIGN KEY (ID_Task)
REFERENCES tbl_Task (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_Item_Questao ADD CONSTRAINT FK_Questao_ItemQuestao
FOREIGN KEY (Questao_ID)
REFERENCES tbl_Questao (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_Alternativa ADD CONSTRAINT FK_Questao_Alternativa
FOREIGN KEY (ID_Questao)
REFERENCES tbl_Questao (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_UsuarioXTask ADD CONSTRAINT FK_Usuario_Task
FOREIGN KEY (ID_Usuario)
REFERENCES tbl_Usuario (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_UsuarioXTask ADD CONSTRAINT FK_Task_Usuario
FOREIGN KEY (ID_Task)
REFERENCES tbl_Task (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_TaskXMateria ADD CONSTRAINT FK_Materia_Task
FOREIGN KEY (ID_Materia)
REFERENCES tbl_Materia (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_TaskXMateria ADD CONSTRAINT FK_Task_Materia
FOREIGN KEY (ID_Task)
REFERENCES tbl_Task (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
 
ALTER TABLE tbl_Resposta ADD CONSTRAINT FK_Usuario_Resposta
FOREIGN KEY (ID_Usuario)
REFERENCES tbl_Usuario (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE tbl_Resposta ADD CONSTRAINT FK_ItemQuestao_Resposta
FOREIGN KEY (ID_ItemQuestao)
REFERENCES tbl_Item_Questao (ID)
ON UPDATE CASCADE
ON DELETE CASCADE;